5. よくあるロジックにトライしよう① 課題提出
yuta10200831/4-question-template pull request #1
Opened 2023-08-06 07:37 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/5-993c8f9c45bf4aa3a50427ad1fc7450b
[作成したページのURL(index.php)]
<img width="1666" alt="スクリーンショット 2023-08-06 16 35 27" src="https://github.com/yuta10200831/4-question-template/assets/124555669/f7dfb809-7084-406f-bc7f-1b7c6c1a031b">

## 作業詳細
spendingsテーブルのamountカラム合計値を出力する
(期待する出力)
<img width="1340" alt="スクリーンショット 2022-07-17 10 04 21" src="https://github.com/yuta10200831/4-question-template/assets/124555669/7b3d2e77-0264-46c7-aa28-91af47b5ba28">

2023-08-07 00:28 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-08-07 00:28 UTC, KatsuyaTanaka95 commented on src/app/spendings.php
> +}
SpendingsCalculatorクラスは削除しましょう！！
calculateTotalSpendingsメソッドは、Spendingsクラスのメソッドにしましょう！
また、、calculateTotalSpendingsメソッドは、staticメソッドにせずでいきましょ〜

2023-08-07 10:12 UTC, yuta10200831 commented on src/app/spendings.php
> +}
修正しました！

2023-08-07 10:15 UTC, yuta10200831 commented
## 作業対象
[作業をした教材のURL]
https://www.notion.so/5-993c8f9c45bf4aa3a50427ad1fc7450b
[作成したページのURL(index.php)]
<img width="1666" alt="スクリーンショット 2023-08-07 19 12 07" src="https://github.com/yuta10200831/4-question-template/assets/124555669/241215d0-7055-4ac0-b64a-98e0518d0d08">

## 作業詳細
・SpendingsCalculatorクラスは削除
・calculateTotalSpendingsメソッドをSpendingsクラスのメソッドにする
・calculateTotalSpendingsメソッドをstaticメソッドから修正

2023-08-08 04:26 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-08-08 09:53 UTC, merged