6. よくあるロジックにトライしよう② 課題提出
yuta10200831/4-question-template pull request #3
Opened 2023-08-08 10:05 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/6-ec0347a95ab24d9c924143f91ebb68bb
[作成したページのURL(index.php)]
<img width="1666" alt="スクリーンショット 2023-08-08 19 00 07" src="https://github.com/yuta10200831/4-question-template/assets/124555669/2292d424-3fdc-456e-9cf4-b6dc1ddd651e">

## 作業詳細
spendingsテーブルのデータを全件取得し、2月の支出を一覧表示する。
(期待する出力)
<img width="1437" alt="スクリーンショット 2022-07-17 8 41 07" src="https://github.com/yuta10200831/4-question-template/assets/124555669/16a45895-8865-4531-ad04-54ace6a1d95a">

2023-08-09 03:07 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-08-09 03:07 UTC, KatsuyaTanaka95 commented on src/app/spendings.php
> +            $display .= $spending["name"] . ": " . $spending["amount"] . "<br/>";
$displayは、配列にし、
displaySpendingForMonthメソッドでは、$display配列を返しましょう！！

2023-08-09 13:01 UTC, yuta10200831 commented on src/app/spendings.php
> +            $display .= $spending["name"] . ": " . $spending["amount"] . "<br/>";
修正しました、
こんな感じですかね、、？

2023-08-09 13:04 UTC, yuta10200831 commented
## 作業対象
[作業をした教材のURL]
https://www.notion.so/6-ec0347a95ab24d9c924143f91ebb68bb
[作成したページのURL(index.php)]
<img width="1666" alt="スクリーンショット 2023-08-09 21 58 27" src="https://github.com/yuta10200831/4-question-template/assets/124555669/30af7126-b160-4fe8-a65b-90c2f7fa7c47">

## 作業詳細
$displayは、配列にし、
displaySpendingForMonthメソッドでは、$display配列を返す

2023-08-10 05:22 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
良いコードですね！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-08-10 09:54 UTC, merged