7. よくあるロジックにトライしよう③　課題②提出
yuta10200831/4-question-template pull request #4
Opened 2023-08-08 14:02 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/7-02f3202f1cbb4e90a9fbd0be629c3b72
[作成したページのURL(index.php)]
<img width="1666" alt="スクリーンショット 2023-08-08 23 00 46" src="https://github.com/yuta10200831/4-question-template/assets/124555669/66bba973-b5f9-4cd4-9c50-35cdbe527470">
<img width="1666" alt="スクリーンショット 2023-08-08 23 01 00" src="https://github.com/yuta10200831/4-question-template/assets/124555669/8048544c-4c30-4568-beca-9b4da1dc0179">

## 作業詳細
spendingsテーブルのデータを全件取得し、支出の低い順にsortして支出を一覧表示する。

(期待する出力)
1600
1800
1800
1800
1800
1800
1900
1900
2000
2100
2100
2100
2200
2300
2300
2300
2300
2300
2300
2300
2300
2400
2400
2800
3000
3000
3000
3000
3000
3000
3500
3800
3800
4000
4000
4000
4000
4000
4000
4000
4000
4000
4000
4000
4000
4000
4100
4400
4500
4500
4500
4500
4500
4600
4600
4600
5000
5000
5000
5000
6300
7000
8000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
13000
13000
63000
63000
63000
63000
63000
63000
63000
63000
63000
63000
63000
63000

2023-08-09 03:50 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-08-09 03:50 UTC, KatsuyaTanaka95 commented on src/app/spendings.php
> +    }
displaySortedSpendingsメソッドは削除しましょう！

q1/task7-2.phpファイルでは、
sortByAmountAscメソットを呼び出しましょう！
そして、、受け取った配列をforeachで出力しましょう！

2023-08-09 03:50 UTC, KatsuyaTanaka95 commented on src/app/spendings.php
> +    }
基本的にメソッドでは、配列や変数を返しましょう！
表示するファイルで、foreach等を使って表示するやり方に慣れていきましょう！

2023-08-09 13:15 UTC, yuta10200831 commented on src/app/spendings.php
> +    }
修正しました！

2023-08-09 13:19 UTC, yuta10200831 commented
## 作業対象
[作業をした教材のURL]
https://www.notion.so/7-02f3202f1cbb4e90a9fbd0be629c3b72
[作成したページのURL(index
<img width="1666" alt="スクリーンショット 2023-08-09 22 17 11" src="https://github.com/yuta10200831/4-question-template/assets/124555669/590dc8e0-27a3-495d-8261-15db07d8ea88">
<img width="1666" alt="スクリーンショット 2023-08-09 22 17 04" src="https://github.com/yuta10200831/4-question-template/assets/124555669/23395236-d8c1-4ee5-a70f-ec9782e443e7">
.php)]

## 作業詳細
displaySortedSpendingsメソッドは削除する。

q1/task7-2.phpファイルでは、
sortByAmountAscメソットを呼び出す。
受け取った配列をforeachで出力する！

2023-08-09 13:20 UTC, yuta10200831 commented
## 作業対象
[作業をした教材のURL]
https://www.notion.so/7-02f3202f1cbb4e90a9fbd0be629c3b72
[作成したページのURL(index
<img width="1666" alt="スクリーンショット 2023-08-09 22 17 11" src="https://github.com/yuta10200831/4-question-template/assets/124555669/590dc8e0-27a3-495d-8261-15db07d8ea88">
<img width="1666" alt="スクリーンショット 2023-08-09 22 17 04" src="https://github.com/yuta10200831/4-question-template/assets/124555669/23395236-d8c1-4ee5-a70f-ec9782e443e7">
.php)]

## 作業詳細
displaySortedSpendingsメソッドは削除する。

q1/task7-2.phpファイルでは、
sortByAmountAscメソットを呼び出す。
受け取った配列をforeachで出力する！

2023-08-10 05:27 UTC, KatsuyaTanaka95 approved these changes
こちらもGoodです！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-08-10 09:55 UTC, merged