9.よくあるロジックにトライしよう　課題②　提出
yuta10200831/4-question-template pull request #8
Opened 2023-08-12 07:40 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/9-b6d32c388eaf404aae8182b7c8c11d89
[作成したページのURL(index.php)]
![スクリーンショット 2023-08-12 16 37 22](https://github.com/yuta10200831/4-question-template/assets/124555669/0e30a3fc-3bc2-41b8-8ea9-60907faa2516)

## 作業詳細
incomesテーブルのデータを全件取得し、前月の収入との差分を[1月~6月の間のぶん]のみ一覧表示しましょう。
(期待する出力)
前月の収入との差分を[1月~6月の間のぶん]のみ一覧表示してください。
1月と2月の差分:　2000円
2月と3月の差分:　5000円
3月と4月の差分:　2000円
4月と5月の差分:　2000円
5月と6月の差分:　10000円

2023-08-17 02:00 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-08-17 02:05 UTC, KatsuyaTanaka95 requested changes
確かに答えが違ってますね！！

サンプルコードのような形で作れるといいですね！！（サンプルコードがよくあるロジックなので、これを練習してほしいです！！！）
` $incomesDifference = abs($totalIncomesAmounts[$i + 1] - $totalIncomesAmounts[$i]);
`
20:00~の研修の際にデバッグの仕方もきいてみましょう！！🙆😊

2023-08-17 14:31 UTC, yuta10200831 commented
コード修正しました！
出力結果変わらずだったのでご確認お願いします。

var_dampをつかってデバックした結果を貼ります！
<img width="1707" alt="スクリーンショット 2023-08-17 23 24 50" src="https://github.com/yuta10200831/4-question-template/assets/124555669/e640ce0a-d7b8-403b-bd1b-7e751926ef69">

ちなみにですが確認です！
・4月と5月の差分:　2000円が正ですか？
　こちら5000円であっていますでしょうか、、
　2000円が正であれば再度修正します！

2023-08-18 06:16 UTC, KatsuyaTanaka95 approved these changes
5000円であってました！！
惑わせてしまってすみません！！
修正していただいたコード素晴らしいです！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-08-18 11:21 UTC, merged